[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pokedex"
dynamic = ["version"]

[project.scripts]
pokedex = "pokedex.pokedex:query"
